name: Build ZMK Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout user config
        uses: actions/checkout@v4

      - name: Clone ZMK
        uses: actions/checkout@v4
        with:
          repository: zmkfirmware/zmk
          path: zmk
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip ninja-build gperf ccache dfu-util wget cmake
          pip3 install west
          west init -l zmk
          west update
          west zephyr-export

      - name: Build (Cradio Left + Nice!Nano v1)
        run: |
          west build -s zmk/app -b nice_nano -- -DSHIELD=cradio_left
          mkdir -p output
          cp build/zephyr/zmk.uf2 output/cradio_left-nice_nano.zmk.uf2

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: output/
