name: Build ZMK Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout user config
        uses: actions/checkout@v4

      - name: Clone ZMK
        run: |
          git clone --recurse-submodules https://github.com/zmkfirmware/zmk.git zmk

      - name: Setup Zephyr project & SDK
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zmk/app
          toolchains: arm-zephyr-eabi

      - name: Build (Cradio Left + Nice!Nano v1)
        run: |
          west build -s zmk/app -b nice_nano -- -DSHIELD=cradio_left
          mkdir -p output
          cp build/zephyr/zmk.uf2 output/cradio_left-nice_nano.zmk.uf2

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: output/
